#!/usr/bin/env ansible-playbook
---
- name: deploy marketcap executable to cron
  hosts: digitalocean
  vars:
    user: "{{ ansible_user }}"
    home: "{{ ansible_env.HOME }}"
    execdir: /root/marketcap/
  tasks:    
    - name: copy compiled file      
      copy:
        src: compiled/
        dest: "{{ execdir }}"
        owner: "{{ user }}"      
        mode: 0740
        
    - name: setup cron job
      cron:
        name: "marketcap"
        minute: "*/10"
        user: "{{ user }}"
        job: "cd {{ execdir }} && ./marketcap"